### ISSUE TITLE
Windows Builds cache misses

### ISSUE THREAD

**Issue by sr229** [vignetteapp/MediaPipe.NET.Runtime#7]
Bulk of the build time is Windows since it keeps finding the build cache that doesn't exist.

**Comment by Speykious** [comment]
**Heads up.**

I think this has been fixed in `actions/cache@v3`.

Checkout [MediaPipeUnityPlugin's Windows test CI](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/.github/workflows/windows-test.yml).
It does manage to [cache the Bazel folder properly](https://github.com/homuler/MediaPipeUnityPlugin/runs/7212800022?check_suite_focus=true).

**Comment by Speykious** [comment]
Welp...
![image](https://user-images.githubusercontent.com/13885008/181636412-50e9af52-5546-4956-81f8-e5f6fd437c72.png)
Seems like we're missing something. We'll have to investigate at one point.

**Comment by sr229** [comment]
Logged in https://github.com/actions/cache/issues/1109

**Comment by sr229** [comment]
Accidentally solved it in GH-16, whoops. Looks like the new v3 runners can cache them now.
